language: cpp
branches:
  except:
  - appveyor
matrix:
  include:
  - os: osx
    osx_image: xcode11.3
    before_install:
    - brew update
    - brew install qt5
    - brew link qt5 --force
    before_deploy:
    - macdeployqt neuronify.app -qmldir=. -dmg
    install:
    - qmake
    - make
    deploy:
      skip_cleanup: true
      provider: releases
      file: neuronify.dmg
      on:
        tags: true
      api_key: $GITHUB_RELEASE_KEY
  - os: linux
    dist: xenial
    services: docker
    addons:
      snaps:
        - name: snapcraft
          channel: stable
          confinement: classic
    install:
    - docker build .travis -t neuronify
    script:
    - docker run -v $(pwd):/app -t neuronify bash -ex .travis/ubuntu.sh
    before_deploy:
    - docker run -v $(pwd):/app -t neuronify bash -c "cd /app/ && snapcraft"
    deploy:
      on:
        #tags: true
        all_branches: true
      provider: snap
      snap: neuronify*.snap
      channel: edge
      cleanup: false
      skip_cleanup: true
script:
- echo "Finished"
sudo: required
services:
- docker
