language: cpp
branches:
  except:
  - appveyor
matrix:
  include:
  - os: osx
    osx_image: xcode10.2
    before_install:
    - brew update
    - brew install qt5
    - brew link qt5 --force
    before_deploy:
    - git clone https://github.com/iltommi/macdeployqtfix.git
    - python macdeployqtfix/macdeployqtfix.py neuronify.app/Contents/MacOS/neuronify
      /usr/local
    - macdeployqt neuronify.app -qmldir=. -dmg
    install:
    - qmake
    - make
    deploy:
      skip_cleanup: true
      provider: releases
      file: neuronify.dmg
      on:
        tags: true
      api_key:
        secure: WJ9YTjPf8GWZ4PmdVoPubtL0CBU+cAIIMFjTpeOKwOLX1vH3zFkdwAz1nbY28CWWhm+YQwWVWwByZOI9hePsf5t6wtkWfJB4wzgrKEcIyKHMHmjaMYc+fp6V//3f7Z4Kc6vYn7wNNy1i9zgA8VVr2A4u8Rf1i7Euio4SLpey17w=
  - os: linux
    dist: trusty
    sudo: required
    services: docker
    install:
    - docker build .travis -t neuronify
    script:
    - docker run -v $(pwd):/app -t neuronify bash -ex .travis/ubuntu.sh
    after_success:
    - openssl aes-256-cbc -K $encrypted_011e1d67e5b5_key -iv $encrypted_011e1d67e5b5_iv
      -in .snapcraft/travis_snapcraft.cfg -out .snapcraft/snapcraft.cfg -d
    deploy:
      on:
        tags: true
      provider: script
      script: docker run -v $(pwd):/app -t neuronify bash -c "cd /app/ && snapcraft
        && snapcraft push *.snap --release edge"
      skip_cleanup: true
script:
- echo "Finished"
sudo: required
services:
- docker
