language: cpp
branches:
  except:
  - appveyor
matrix:
  include:
  - os: osx
    before_install:
    - brew update
    - brew install p7zip
    - bash .travis/qt5-mac.sh $(pwd) extra-charts 3d base declarative graphicaleffects
      imageformats macextras multimedia quickcontrols quickcontrols2 sensors svg tools
      translations xmlpatterns
    - export PATH=$(pwd)/5.7/clang_64/bin:$PATH
    before_deploy:
    - git clone https://github.com/iltommi/macdeployqtfix.git
    - python macdeployqtfix/macdeployqtfix.py neuronify.app/Contents/MacOS/neuronify
      /usr/local
    - macdeployqt neuronify.app -qmldir=. -dmg
    install:
    - qmake
    - make
    deploy:
      skip_cleanup: true
      provider: releases
      file: neuronify.dmg
      'on':
        tags: true
      api_key:
        secure: WJ9YTjPf8GWZ4PmdVoPubtL0CBU+cAIIMFjTpeOKwOLX1vH3zFkdwAz1nbY28CWWhm+YQwWVWwByZOI9hePsf5t6wtkWfJB4wzgrKEcIyKHMHmjaMYc+fp6V//3f7Z4Kc6vYn7wNNy1i9zgA8VVr2A4u8Rf1i7Euio4SLpey17w=
  - os: linux
    dist: trusty
    sudo: required
    services: docker
    install:
    - docker
    - docker run -v $(pwd):/app ubuntu:16.04 bash -c "cd /app/ && bash -ex .travis/ubuntu.sh"
    after_success:
    - openssl aes-256-cbc -K $encrypted_8bc7dae8784d_key -iv $encrypted_8bc7dae8784d_iv
      -in .snapcraft/.snapcraft/travis_snapcraft.cfg -out .snapcraft/.snapcraft/snapcraft.cfg -d
    deploy:
      'on':
        branch: dev
      provider: script
      script: docker run -v $(pwd):/app ubuntu:16.04 bash -c "cd /app/.snapcraft && snapcraft && snapcraft push *.snap --release edge"
      skip_cleanup: true
script:
- echo "Finished"
sudo: required
services:
- docker
