name: Build pushed commit

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macOS-latest, ubuntu-latest, ubuntu-20.04]
        version: ['5.15.1']
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          modules: "qtcharts qtmultimedia qtmultimediawidgets qtsql"
          tools: "tools_ifw,4.0,qt.tools.ifw.40"
      - name: Build on Windows
        if: startsWith(matrix.os, 'windows')
        shell: cmd
        run: |
          call "%programfiles(x86)%\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          qmake
          nmake
          set INSTALLER_DIR=installer\packages\net.ovilab.neuronify\data\
          xcopy /s "release" "%INSTALLER_DIR%"
          xcopy /s "%Qt5_DIR%\qml" "%INSTALLER_DIR%"
          xcopy /s "%Qt5_DIR%\bin\Qt5MultimediaQuick.dll" "%INSTALLER_DIR%"
          echo dir qt5
          dir "%Qt5_DIR%"
          echo dir qt5 ..
          dir "%Qt5_DIR%\.."
          echo dir qt5 ..
          dir "%Qt5_DIR%\..\.."
          echo dir
          dir
          echo dir installer
          dir "%INSTALLER_DIR%"
          echo windeployqt
          windeployqt.exe -quick -quickwidgets -multimedia -opengl -quickparticles -quickwidgets -qmldir . "%INSTALLER_DIR%"
          echo binarycreator
          "%Qt5_DIR%\..\..\Tools\QtInstallerFramework\4.0\bin\binarycreator.exe" -c installer/config/config.xml -p installer/packages neuronify-windows-installer
      - name: Build on MacOS
        if: startsWith(matrix.os, 'mac')
        run: |
          mkdir build
          cd build
          qmake ..
          make
          macdeployqt neuronify.app -qmldir=. -dmg
      - name: Build snap
        uses: snapcore/action-build@v1
        if: startsWith(matrix.os, 'ubuntu')
        id: buildsnap
      - name: Publish snap
        uses: snapcore/action-publish@v1
        if: startsWith(matrix.os, 'ubuntu')
        with:
          store_login: ${{ secrets.SNAP_STORE_LOGIN }}
          snap: ${{ steps.buildsnap.outputs.snap }}
          release: edge
      - name: Build on Ubuntu
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          mkdir build
          cd build
          qmake ..
          make
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: build
