name: Build pushed commit

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macOS-latest, ubuntu-latest, ubuntu-20.04]
        version: ['5.15.1']
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          modules: "qtcharts qtmultimedia qtmultimediawidgets qtsql"
      - name: Build on Windows
        if: startsWith(matrix.os, 'windows')
        shell: cmd
        run: |
          call "%programfiles(x86)%\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          qmake .
          nmake
      - name: Build on Unix
        if: (!startsWith(matrix.os, 'windows'))
        run: |
          mkdir build
          cd build
          qmake ..
          make
